### ISSUE TITLE
View rendering throws error

### ISSUE THREAD

**Issue by KeKs0r** [stonecircle/kue-ui#19]
Tried a very basic setup, but can't get it working
My Setup

```
    var q = kue.createQueue({
        prefix: 'q',
        redis: {
            port: options.port,
            host: options.host,
            auth: options.password
        }
    });

    s.expose('queue', q);
    s.expose('kue', kue);

    // Admin UI
    //kue.app.mountpath = '/admin/kue';
    // Otherwise u cant run tests while having a server running;
    var port = Math.floor(Math.random() * 1000) + 16000;
    console.log('local port!'+port);
    var app = express();


    ui.setup({
        apiURL: '/api', // IMPORTANT: specify the api url
        baseURL: '/kue', // IMPORTANT: specify the base url
        updateInterval: 5000 // Optional: Fetches new data every 5000 ms
    });

    // Mount kue JSON api
    app.use('/api', kue.app);
    // Mount UI
    app.use('/kue', ui.app);

    app.listen(port);
```

The error

```
TypeError: Cannot read property '0' of undefined
    at new View (/Users/marc/Sites/hapigamb/node_modules/express/lib/view.js:41:65)
    at Function.app.render (/Users/marc/Sites/hapigamb/node_modules/express/lib/application.js:485:12)
    at ServerResponse.res.render (/Users/marc/Sites/hapigamb/node_modules/express/lib/response.js:755:7)
    at clientRoute (/Users/marc/Sites/hapigamb/node_modules/kue-ui/lib/kue-ui.js:14:16)
    at callbacks (/Users/marc/Sites/hapigamb/node_modules/kue-ui/node_modules/express/lib/router/index.js:164:37)
    at param (/Users/marc/Sites/hapigamb/node_modules/kue-ui/node_modules/express/lib/router/index.js:138:11)
    at pass (/Users/marc/Sites/hapigamb/node_modules/kue-ui/node_modules/express/lib/router/index.js:145:5)
    at Router._dispatch (/Users/marc/Sites/hapigamb/node_modules/kue-ui/node_modules/express/lib/router/index.js:173:5)
    at Object.router (/Users/marc/Sites/hapigamb/node_modules/kue-ui/node_modules/express/lib/router/index.js:33:10)
    at next (/Users/marc/Sites/hapigamb/node_modules/kue-ui/node_modules/express/node_modules/connect/lib/proto.js:174:15)
    at Object.expressInit [as handle] (/Users/marc/Sites/hapigamb/node_modules/kue-ui/node_modules/express/lib/middleware.js:30:5)
    at next (/Users/marc/Sites/hapigamb/node_modules/kue-ui/node_modules/express/node_modules/connect/lib/proto.js:174:15)
    at Object.query [as handle] (/Users/marc/Sites/hapigamb/node_modules/kue-ui/node_modules/express/node_modules/connect/lib/middleware/query.js:43:5)
    at next (/Users/marc/Sites/hapigamb/node_modules/kue-ui/node_modules/express/node_modules/connect/lib/proto.js:174:15)
    at Function.app.handle (/Users/marc/Sites/hapigamb/node_modules/kue-ui/node_modules/express/node_modules/connect/lib/proto.js:182:3)
    at Object.fn [as handle] (/Users/marc/Sites/hapigamb/node_modules/express/lib/application.js:117:11)
```

**Comment by mansona** [comment]
This is no longer relevant to this particular repository. If you could try out https://github.com/stonecircle/kue-ui-express and let me know there if you have the same issue that would be great 👍
