### ISSUE TITLE
git clone && npm install fails

### ISSUE THREAD

**Issue by flower1024** [stonecircle/kue-ui#49]
npm ERR! Command failed: /usr/bin/git checkout feature/fixCSSClean
npm ERR! error: pathspec 'feature/fixCSSClean' did not match any file(s) known to git.

**Comment by Raidus** [comment]
same here

**Comment by allenh** [comment]
I got the same error as well.
Here is what the npm logs have:

```
2738 silly fetchPackageMetaData error for ember-cli-notifications@github:stonecircle/ember-cli-notifications#feature/fixCSSClean Command failed: /usr/bin/git checkout feature/fixCSSClean
2738 silly fetchPackageMetaData error: pathspec 'feature/fixCSSClean' did not match any file(s) known to git.
2739 verbose stack Error: Command failed: /usr/bin/git checkout feature/fixCSSClean
2739 verbose stack error: pathspec 'feature/fixCSSClean' did not match any file(s) known to git.
2739 verbose stack
2739 verbose stack     at ChildProcess.exithandler (child_process.js:275:12)
2739 verbose stack     at emitTwo (events.js:126:13)
2739 verbose stack     at ChildProcess.emit (events.js:214:7)
2739 verbose stack     at maybeClose (internal/child_process.js:925:16)
2739 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
2740 verbose cwd /Users/weiping/Documents/projects/kue-ui
2741 verbose Darwin 16.7.0
2742 verbose argv "/usr/local/Cellar/node/8.9.2/bin/node" "/usr/local/bin/npm" "install"
2743 verbose node v8.9.2
2744 verbose npm  v5.5.1
2745 error code 1
2746 error Command failed: /usr/bin/git checkout feature/fixCSSClean
2746 error error: pathspec 'feature/fixCSSClean' did not match any file(s) known to git.
2747 verbose exit [ 1, true ]
```

**Comment by gofreddo** [comment]
+1

**Comment by takion** [comment]
+1

**Comment by QmarXX** [comment]
I need to change 
```
"ember-cli-notifications": "stonecircle/ember-cli-notifications#feature/fixCSSClean",
```
to 
```
"ember-cli-notifications": "stonecircle/ember-cli-notifications#v4.2.1",
```
in `package.json`

Also i need to change `ENV.apiURL` in `config/environment.js` to `http://localhost:3050` and install https://addons.mozilla.org/pl/firefox/addon/cors-everywhere/ to disable CORS.
